name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Build
      run: npm run build
      env:
        EDGE_CONFIG: ${{ secrets.EDGE_CONFIG }}
        EDGE_CONFIG_ID: ${{ secrets.EDGE_CONFIG_ID }}
        VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}

